secrets:
  - kmsKeyName: projects/infostellar-cluster/locations/us-central1/keyRings/cloudbuild/cryptoKeys/deploy-stubs
    secretEnv:
      MAVEN_PASSWORD: CiQAo3bGoYXB3hVouZrQjQ49Na9nyfRP9p2eei0qkWApr6bAziISVQD6f46OpEZCBVyO4jUoPzlmBdv1GGV8r8AxPZVYcqfR8uqUZEzwht2tnmkN9UxGEtAe6RAr5XNh2YTlVCTmQ4oHVklPb6NgqzgOiCg/bB+uYXXqros=
      SIGNING_PASSWORD: CiQAo3bGoVnvC+dNthiI+dAFswbsvn9/j9a3TW8javB0kFQmDyoSSQD6f46O064kepbO3EoGMcB1Zu9iCJSk3tjkHc/Rl3SUjcr18R85/lWiWWi7tVu7J0Vkdbs3wncKaAr93uUWV9WqQH5LKcwNlGk=
      NPM_KEY: CiQAo3bGoRJ721LzjFjReYDlNaQnml+KdXtUFlhNcxjTLu0EI/ISTQD6f46ObEDBR7Sfp2ghkjd2C12bHgjeple0Yt2DctBcumNYT0Ic7s0po4GSFEEX1QVKkFALZZrkCtAv/4prRoZmZlRdm7Ns1Otjvgq4
      PYPI_KEY: CiQAo3bGoYxDEMHcyJkPIdmcvbfRIbet09HVwIPrxhAGKP3UHGESNQD6f46OLClPEFS8FpMcW+AXpBrxGkJEkY1dGj3iziGQVvGbULd4Mh3/vXQEPU14d2MC/NaC
steps:
- name: gcr.io/cloud-builders/gcloud
  args:
    - kms
    - decrypt
    - --ciphertext-file=cloudbuild/id_rsa.enc
    - --plaintext-file=cloudbuild/id_rsa
    - --location=us-central1
    - --keyring=cloudbuild
    - --key=deploy-stubs
- name: gcr.io/cloud-builders/gcloud
  args:
    - kms
    - decrypt
    - --ciphertext-file=cloudbuild/secring.gpg.enc
    - --plaintext-file=cloudbuild/secring.gpg
    - --location=us-central1
    - --keyring=cloudbuild
    - --key=deploy-stubs
- id: publish-release
  name: curiostack/java-cloud-builder
  entrypoint: bash
  args:
    - -c
    # The SSH clients are looking in /root/.ssh for keys and config, even although the HOME directory
    # is /builder/home.
    - |
      mkdir /root/.ssh &&
      cp cloudbuild/id_rsa /root/.ssh/id_rsa &&
      chmod 400 /root/.ssh/id_rsa &&
      apt-get -y update &&
      apt-get -y install binutils &&
      echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> /root/.ssh/config &&
      ./gradlew -Ppypi.user=istellar-sysadmin -Ppypi.password=$$PYPI_KEY -Pmaven.username=UpVSp/UZ -Pmaven.password=$$MAVEN_PASSWORD -Psigning.secretKeyRingFile="$(pwd)/cloudbuild/secring.gpg" -Psigning.keyId=C8772BE9 -Psigning.password=$$SIGNING_PASSWORD -Pnpm.key=$$NPM_KEY -Pcuriostack.release=true --stacktrace --no-daemon publishStubs
  secretEnv:
  - MAVEN_PASSWORD
  - SIGNING_PASSWORD
  - NPM_KEY
  - PYPI_KEY
  env:
  - CI=true
  - TAG_NAME=$TAG_NAME
  - BRANCH_NAME=$BRANCH_NAME
timeout: 60m
options:
  machineType: N1_HIGHCPU_32
