# CURRENTLY BROKEN, WORK IN PROGRESS TO FIX

steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=cloudbuild/id_rsa.enc
  - --plaintext-file=cloudbuild/id_rsa
  - --location=us-central1
  - --keyring=cloudbuild
  - --key=deploy-stubs
- name: curiostack/java-cloud-builder
  entrypoint: bash
  args:
  - -c
  # The SSH clients are looking in /root/.ssh for keys and config, even although the HOME directory
  # is /builder/home.
  - |
    mkdir /root/.ssh &&
    cp cloudbuild/id_rsa /root/.ssh/id_rsa &&
    chmod 400 /root/.ssh/id_rsa &&
    echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> /root/.ssh/config &&
    ./gradlew :stubs:golang:gitPublishPush --stacktrace --no-daemon
  env:
    - CI=true
    - CI_MASTER=true
timeout: 60m
options:
  machineType: N1_HIGHCPU_32
