syntax = "proto3";

import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";
import "stellarstation/api/v1/orbit/orbit.proto";
import "stellarstation/api/v1/radio/radio.proto";
import "stellarstation/api/v1/transport.proto";
import "stellarstation/api/v1/stellarstation.proto";

package stellarstation.api.v1.reservations;

option go_package = "github.com/infostellarinc/go-stellarstation/api/v1";

option java_multiple_files = true;
option java_outer_classname = "Reservations";
option java_package = "com.stellarstation.api.v1.reservations";

service ReservationService {
  rpc OpenStream(stream SatelliteStreamRequest) returns (stream SatelliteStreamResponse);

  rpc ListPasses(ListPassesRequest) returns (ListPassesResponse);

  rpc GetReservation(GetReservationRequest) returns (GetReservationResponse);
  rpc ListReservations(ListReservationsRequest) returns (ListReservationsResponse);
  rpc CreateReservation(CreateReservationRequest) returns (CreateReservationResponse);
  rpc UpdateReservation(UpdateReservationRequest) returns (UpdateReservationResponse);
  rpc CancelReservation(CancelReservationRequest) returns (CancelReservationResponse);

  rpc AddTle(AddTleRequest) returns (AddTleResponse);
  rpc GetTle(GetTleRequest) returns (GetTleResponse);
  rpc SetTleSource(SetTleSourceRequest) returns (SetTleSourceResponse);
}

message ListPassesRequest {
  string satellite_id = 1;
}

message ListPassesResponse {
  repeated Pass passes = 1;
}

message CreateReservationRequest {
  repeated ChannelSetToken channel_sets = 1;
}

message CreateReservationResponse {
  Reservation reservation = 1;
}

message UpdateReservationRequest {
  string reservation_id = 1;
  repeated ChannelSetToken channel_sets = 2;
}

message UpdateReservationResponse {
  Reservation reservation = 1;
}

message CancelReservationRequest {
  string reservation_id = 1;
}

message CancelReservationResponse {
  Reservation reservation = 1;
}

message GetReservationRequest {
  string reservation_id = 1;
}

message GetReservationResponse {
  Reservation reservation = 1;
}

message ListReservationsRequest {
  string satellite_id = 1;
  TimeRange visibility = 2;
}

message ListReservationsResponse {
  repeated Reservation reservations = 1;
}

message Reservation {
  string id = 1;

  Satellite satellite = 2;
  GroundStation ground_station = 3;

  Status status = 4;
  TimeRange visibility = 5;
  TimeRange operation = 6;
  double max_elevation = 7;
  bool drifted = 8;

  repeated ChannelSetToken channel_sets = 9;

  enum Status {
    Status_UNKNOWN = 0;
    Status_RESERVED = 1;
    Status_EXECUTING = 2;
    Status_COMPLETED = 3;
    Status_FAILED = 4;
    Status_CANCELLED = 5;
  }
}

message Pass {
  // The visibility time (AOS-LOS) between the ground station and the satellite.
  // - visibility.start = AOS (Aquisitation Of Signal)
  // - visibility.end = LOS (Loss Of Signal)
  TimeRange visibility = 1;

  Satellite satellite = 2;

  // Information about the ground station of the pass.
  GroundStation ground_station = 3;

  // The available and reservable channel set options.
  // Channel sets are divided into slots for compatibility. You cannot schedule 2 channel sets from the same slot. The request will be rejected.
  repeated ChannelSetToken channel_sets = 4;

  // The max elevation during the pass, in degrees.
  double max_elevation_degrees = 5;
  // The time of the max elevation during the pass.
  google.protobuf.Timestamp max_elevation_time = 6;
}

message ChannelSetToken {
  string id = 1;
  string name = 2;
  string token = 3;
  string slot = 4;
  bool scheduled = 5;
}

message TimeRange {
  google.protobuf.Timestamp start = 1;
  google.protobuf.Timestamp end = 2;
}

message Satellite {
  string id = 1;
  string name = 2;
  string organization = 3;
}

message GroundStation {
  // The unique ID of the ground station.
  string id = 1;
  // A descriptive name for the ground station.
  string name = 2;
  // The owning organization of the ground station.
  string organization = 3;
  // The latitude of the ground station.
  double latitude = 4;
  // The longitude of the ground station.
  double longitude = 5;
  // The altitude of the ground station.
  double altitude = 6;
}
